-   hosts: all
    vars_files:
      - "group_vars/vault.yml"
    vars:
        playbook_name: 'oneoff'
        # Defined in all.yml and
        #        mount_dir: /mnt/efs/apt

        centrallogs:
          - { name: nginx, logdir: /var/log/nginx-new, servicename: nginx}
          - { name: unattended-upgrades, logdir: /var/log/unattended-upgrades-new }
          - { name: supervisor, logdir: /var/log/supervisor-new, servicename: supervisor }
            #         - {name: pharos, logdir: "/var/www/{{ansible_fqdn}}/pharos/shared/log", servicename: nginx}

    roles:
      #      - common
      - { role: central_logs, tags: centrallogs}



    tasks:
