---
# Setting up VisualEditor

- name: Install npm
  become_user: "{{system_default_user}}
  shell: curl -sL https://deb.nodesource.com/setup_4.x  | sudo -E bash -
  register: addnpm

- name: Install node.js
  apt: name=nodejs
  become: true
  when: addnpm

- name: install parsoid
  npm: name=parsoid path={{mediawiki_path}}/parsoid
  tags: parsoid

- name: Config parsoid
  shell: cp config.example.yaml config.yaml
  args:
    chdir: "{{mediawiki_path}}/parsoid"
  tags: parsoid

- name: Update parsoid config
  lineinfile: dest="{{mediawiki_path}}/parsoid/config.yml"
  line: 'https://{{hostname_fqdn}}/api.php'
  regexp: 'http://localhost/w/api.php'

- name: Update parsoid config
  lineinfile: dest="{{mediawiki_path}}/parsoid/config.yml"
  line: 'aptrust.org'
  regexp: "domain:'localhost'"

- name: Update mediawiki config
  blockinfile: dest="{{mediawiki_path}}/LocalSettings.yml"
              insertafter="wfLoadExtension\( \'VisualEditor\'\ )\;"
              content= |
								$wgVirtualRestConfig\['modules'\]\['parsoid'\] = array(
									// URL to the Parsoid instance
									// Use port 8142 if you use the Debian package
									'url' => 'https://{{hostname_fqdn}}:8000',
									// Parsoid "domain", see below (optional)
									'domain' => '{{ansible_domain}}',
									// Parsoid "prefix", see below (optional)
									'prefix' => '{{ansible_domain}}'
								);
              state=present
