---
allow_duplicates: no

galaxy_info:
  author: Chris Baptista
  description: npm installation
  company:
  license: license (BSD)
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
    - packaging
    - development
