---
  - name: Clone additional plugins
    git: repo="https://github.com/harisekhon/nagios-plugins"
         dest="{{nagios_plugin_dir}}/nagios-plugins"
         force=yes
    register: gitpull
    tags: nagios-additional-plugins

  - name: Compile plugins and install requisites (takes a while)
    shell: chdir="{{nagios_plugin_dir}}/nagios-plugins" make update
    become: true
    when: gitpull.changed
    tags: nagios-additional-plugins

  - name: Add custom plugins to constants.conf
    lineinfile: >
        dest="{{icinga2_const_conf}}"
        line="const AdditionalPluginDir=\"{{nagios_plugin_dir}}/nagios-plugins\""
        regexp="^const AdditionalPluginDir=\"{{nagios_plugin_dir}}/nagios-plugins\""
        state=present
    notify: restart icinga2
    tags: nagios-additional-plugins
