- name: Add managed vhost config file (if any vhosts are configured).
  template:
        src: nginx_vhost.conf.j2
        dest: "{{ nginx_vhost_path }}/{{ nginx_vhost_filename }}"
        mode: 0644
        group: "{{ nginx_group}}"
  when: nginx_vhosts|length > 0
  notify: nginx reload

- name: Remove managed vhost config file (if no vhosts are configured).
  file:
    path: "{{ nginx_vhost_path }}/{{ nginx_vhost_filename }}"
    state: absent
  when: not nginx_vhosts
  notify: nginx reload
