---
# Identify type of server, DPN or APTrust. Default to apt.
- name: Is this an APT or DPN Server
  set_fact: orgtype="{% if 'dpn' in ansible_hostname%}dpn{%else%}apt{%endif%}"
  tags: [always, mountdir]

- name: Check if EFS mount exists
  command: "mountpoint {{mount_dir}}/{{orgtype}}"
  register: mount_stat
  #  changed_when: False
  failed_when: False

- name: If logs already symlinked, ignore the rest..
  stat: path="{{item.logdir}}"
  register: logssym
  with_items: "{{centrallogs}}"
  tags: symdeb

  #- debug: var=logssym.results[0].stat.islnk
  # tags: symdeb

- name: temporarily disable this check for testing.
  set_fact: mount_stat.rc = 0

- include: symlink.yml
  with_items:
    - "{{centrallogs}}"
    - logssym.results
  #  when: mount_stat.rc == 0 and (logssym.stat.islnk is defined and logssym.stat.islnk == false)
  #  when: mount_stat.rc == 0
  when: logssym.results[0].stat.islnk == False
  loop_control:
      loop_var: logssym.results
  # NOTE: THIS DOES NOT WORK WIHT A DICT OF MULTIPLE LOGDIRS. THE CONDITIONAL DOESNT
  # EVAL EVERY ITEM IN THE RESULTS LIST. NEED TO ITERATE THROUGH THE LIST SOMEHOW OR RECREATE
  # A LIST OF ONLY NON SYMLINKED ITEMS.

